---
abstract: 'Class automation, introspection, and data validation'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Meta
provides:
  Class::Meta:
    file: lib/Class/Meta.pm
    version: 0.64
  Class::Meta::AccessorBuilder:
    file: lib/Class/Meta/AccessorBuilder.pm
    version: 0.64
  Class::Meta::AccessorBuilder::Affordance:
    file: lib/Class/Meta/AccessorBuilder/Affordance.pm
    version: 0.64
  Class::Meta::AccessorBuilder::SemiAffordance:
    file: lib/Class/Meta/AccessorBuilder/SemiAffordance.pm
    version: 0.64
  Class::Meta::Attribute:
    file: lib/Class/Meta/Attribute.pm
    version: 0.64
  Class::Meta::Class:
    file: lib/Class/Meta/Class.pm
    version: 0.64
  Class::Meta::Constructor:
    file: lib/Class/Meta/Constructor.pm
    version: 0.64
  Class::Meta::Method:
    file: lib/Class/Meta/Method.pm
    version: 0.64
  Class::Meta::Type:
    file: lib/Class/Meta/Type.pm
    version: 0.64
  Class::Meta::Types::Boolean:
    file: lib/Class/Meta/Types/Boolean.pm
    version: 0.64
  Class::Meta::Types::Numeric:
    file: lib/Class/Meta/Types/Numeric.pm
    version: 0.64
  Class::Meta::Types::Perl:
    file: lib/Class/Meta/Types/Perl.pm
    version: 0.64
  Class::Meta::Types::String:
    file: lib/Class/Meta/Types/String.pm
    version: 0.64
recommends:
  Test::Pod: 1.20
requires:
  Class::ISA: 0.31
  Data::Types: 0.05
resources:
  bugtracker: http://github.com/theory/class-meta/issues/
  homepage: http://search.cpan.org/dist/Class-Meta/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/class-meta/
version: 0.64
