--- #YAML:1.0
name: Class-Meta
version: 0.10
license: perl
distribution_type: module
requires:
  Class::ISA: 0.31
  Data::Types: 0.05
recommends: {}
build_requires:
  Test::Simple: 0.17
conflicts: {}
provides:
  Class::Meta:
    file: lib/Class/Meta.pm
    version: 0.10
  Class::Meta::AccessorBuilder:
    file: lib/Class/Meta/AccessorBuilder.pm
    version: 0.10
  Class::Meta::AccessorBuilder::Affordance:
    file: lib/Class/Meta/AccessorBuilder/Affordance.pm
    version: 0.10
  Class::Meta::Attribute:
    file: lib/Class/Meta/Attribute.pm
    version: 0.10
  Class::Meta::Class:
    file: lib/Class/Meta/Class.pm
    version: 0.10
  Class::Meta::Constructor:
    file: lib/Class/Meta/Constructor.pm
    version: 0.10
  Class::Meta::Method:
    file: lib/Class/Meta/Method.pm
    version: 0.10
  Class::Meta::Type:
    file: lib/Class/Meta/Type.pm
    version: 0.10
  Class::Meta::Types::Boolean:
    file: lib/Class/Meta/Types/Boolean.pm
    version: 0.10
  Class::Meta::Types::Numeric:
    file: lib/Class/Meta/Types/Numeric.pm
    version: 0.10
  Class::Meta::Types::Perl:
    file: lib/Class/Meta/Types/Perl.pm
    version: 0.10
  Class::Meta::Types::String:
    file: lib/Class/Meta/Types/String.pm
    version: 0.10
generated_by: Module::Build version 0.21
